name: Web Automation
#on: [push, pull_request]
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select where to run'
        required: true
        default: 'github'
        type: choice
        options:
          - github
      browser:
        description: 'Select browser'
        type: choice
        options:
          - chrome
          - firefox
          - edge
          - electron
      tags:
        description: 'Enter cucumber tags'
        required: false
        type: string
      artifacts:
        description: 'Artifact reporting'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Node JS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies
          run:  npm install
        - name: Run Web Automation
          run: |
            if [ "${{ github.event.inputs.tags }}" ]; then
              npx cypress run -e TAGS='"${{ github.event.inputs.tags }}"' --browser ${{ github.event.inputs.browser }} --config video=false
            else
              npx cypress run --browser ${{ github.event.inputs.browser }} --config video=false
            fi
          continue-on-error: false
        - name: Generate Report
          uses: actions/upload-artifact@v3
          with:
            name: reports
            path: ./cypress/reports