name: Web Automation
#on: [push, pull_request]
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select where to run'
        required: true
        default: 'github'
        type: choice
        options:
        - github
      tags:
        description: 'Enter cucumber tags'
        required: false
        type: string
      artifacts:
        description: 'Artifact reporting'
        required: false
        type: boolean

jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Node JS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies
          run:  npm install
        - name: Run Web Automation
          run: |
            if [ ${{ github.event.inputs.tags }} ]; then
              echo "${{ github.event.inputs.tags }}"
              npx cypress run -e TAGS='${{ github.event.inputs.tags }}' --browser chrome
            fi
          continue-on-error: false
        - name: Generate Report
          uses: actions/upload-artifact@v3
          with:
            name: reports
            path: ./cypress/reports